[project]
name = "hiddensnake"
version = "1.0.2"
description = "Steganographic tools library"
readme = "README.md"
requires-python = "<=3.11.3"
dependencies = [
    "pypng",
]

[project.urls]
Repository = "https://github.com/MichalHer/hiddensnake"