[project]
name = "hiddensnake"
version = "1.0.0"
description = "Steganographic tools library"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pypng",
]

[project.urls]
Repository = "https://github.com/MichalHer/hiddensnake"